[theme]
base = "dark"
primaryColor = "#22ff88"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161a23"
textColor = "#e6e6e6"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
